#Propiedades mario

MAX_HORIZONTAL_JUMP_LENGTH = 11
MAX_VERTICAL_JUMP_LENGTH= 4

#Parametros AE_Generator

MUTATION_PROBABILITY = 0.1
NUMBER_OF_GENERATIONS = 10
NUMBER_OF_PARENTS = 2
SOL_PER_POP = 5
PARENT_SELECTION_TYPE = "random"
MUTATION_BY_REPLACEMENT = True
