#Propiedades mario

MAX_HORIZONTAL_JUMP_LENGTH = 11
MAX_VERTICAL_JUMP_LENGTH= 4

#Parametros AE_Generator

MUTATION_PROBABILITY = 0.05
NUMBER_OF_GENERATIONS = 2
NUMBER_OF_PARENTS = 2
SOL_PER_POP = 5
CROSSOVER_TYPE = "single_point"
PARENT_SELECTION_TYPE = "random"
MUTATION_BY_REPLACEMENT = True
MUTATION_TYPE = "random"
GENE_SPACE = [x for x in range(1, 35)]
